version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db_container
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env-prod
    ports:
      - 5432:5432

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env-prod
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db_data:
